---
extends:
  - 'airbnb'
  - "plugin:import/errors"
  - "plugin:import/warnings"
parser: "babel-eslint"
env:
  browser: true
  jasmine: true
  jquery: true
globals:
  cccFunctions: true
  d3: true
  Promise: true
rules:
  no-console:
    - "error"
    - allow: ["warn"]
  indent: ["error", 2]
  react/jsx-indent: ["error", 2]
  react/jsx-indent-props: ["error", 2]
  import/extensions: "off"
  import/no-extraneous-dependencies: "off"
  jsx-a11y/label-has-for: "off"
  jsx-a11y/label-has-associated-control: "off"
  react/jsx-props-no-spreading: "off"
  react/destructuring-assignment: "off"

