version: '3.1'

services:
  scanomatic:
    privileged: true
    build: .
    ports: ["5000:5000"]
    volumes:
      - ${SOM_SETTINGS:-/tmp/.scan-o-matic}:/root/.scan-o-matic
      - ${SOM_PROJECTS_ROOT:-/tmp/SoM}:/somprojects
      - /dev/bus/usb:/dev/bus/usb
