version: '3.1'

services:
  scanomatic:
    privileged: true
    build: .
    ports: ["5000:5000"]
    volumes:
      - scan-o-matic-home:/root/.scan-o-matic
      - ${SOM_PROJECTS_ROOT:-/tmp/SoM}:/somprojects
      - /dev/bus/usb:/dev/bus/usb

volumes:
  scan-o-matic-home: {}
